### ISSUE TITLE
Unable to Update Dbix Wallet from old version of DBIX wallet

### ISSUE THREAD

**Issue by Aman524** [dubaicoin-dbix/dbixwall#2]
Hi
I was using DbixWall-WinGUIv1.0.1_49-2 way back in June'2017. 
Today i came back to mine DBIX and i am not able to receive new coins into my wallet. Last block on the in the software is 63441
I downloaded DbixWall v2.2, 
Still giving the following error
"Gdbix version older than 1.5.1 is not longer supported pls update gdbix to 1.5.1+"
Pls help me solve the issue...
Thanks

**Comment by Aman524** [comment]
Updating only gdbix file to the next update and restart 
again updated gdbix file and again restart... and so on....to the latest solved the problem.

**Comment by rocky3xr** [comment]
Hey mate did you solve the problem? I have the same issue! and I can not connect
